name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      # Install dependencies
      - name: Install dependencies
        run: npm ci
      
      # Cache Nx
      - uses: nrwl/nx-set-shas@v3

      # Run affected lint
      - name: Lint affected projects
        run: npx nx affected --target=lint --parallel=3
      
      # Run affected tests
      - name: Test affected projects
        run: npx nx affected --target=test --parallel=3
      
      # Run affected build
      - name: Build affected projects
        run: npx nx affected --target=build --parallel=3
      
      # Optional: Connect to Nx Cloud
      - name: Connect to Nx Cloud
        run: npx nx connect-to-nx-cloud
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
